### ISSUE TITLE
Page Content: Create a Business Plan

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#1]
*From Patrick*
1. Create a Business Plan
LEARN

You’re on the road to starting your business, but you’re not sure where you want to go or how long it will take. Let’s define that path by creating a business plan together. 

You will need:
Executive Summary
Business Description
Market Analysis
Organization & Management
Service or Product Line
Marketing & Sales
Finances
Appendix & Supporting Documents
DO 
Write the Business Plan
Show it to people to get feedback
Work with the Long Beach Small Business Development Center to finalize

**Comment by rossettistone** [comment]
*Expanded a little on the bullet points, and omitted the "Appendix & Supporting Documents" point, as I'm not sure that the purpose of that point is clear to people without more context or examples.*

----------

Before you start your business, it's important to have a clear plan for how your business will operate and make money. Writing a business plan will help you prepare for the rest of the business setup process.

LEARN
Every business is a little different, but here are the pieces of a typical business plan:

• __Executive Summary__: A few sentences that give an overview of your business, describing the product or service and your goals for the next year or two.
• __Market Analysis__: Who are the target customers for the business? Are there any businesses providing the same service that might be in competition with your business? Would a particular location in the city be important for your business to succeed?
• __Organization & Management__: Think about what it will take to run the business each day. Will you need employees? What will the hours of the business be? Will you close for weekends and holidays?
• __Service or Product__: Each product that you sell costs something to make, and each service that you provide takes employee time. Whether you're providing a product or a service, carefully calculate your costs so that you know how much you need to charge customers in order to make money.
• __Marketing & Sales__: Every business needs a way to get customers. Write a little about how you plan to advertise and sell, and make sure to note what those marketing and sales activities will cost.
• __Finances__: Using your estimates of what it will cost to open your business, operate, do marketing, and sell to customers, calculate how much money you need to start. If you don't have enough, think about how to borrow additional money. (link to finance page?)

DO
(links to 2-3 example business plans that follow the pattern above)
1) Write a business plan.
2) Show it to people you trust, and ask for feedback.
3) Get free professional advice from SBDC and SCORE (links to sign up).

**Comment by patrickm02L** [comment]
:+1:
