### ISSUE TITLE
Add Glossary Content

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#105]

**Comment by lisaratner** [comment]
https://docs.google.com/document/d/1jnoRRRS51LcwrQr2LFEyg6pI1f9WlnlkSA-bFwXkCVo/edit?usp=sharing

**Comment by rossettistone** [comment]
You can now add glossary items at http://bizport.longbeach.gov/admin/glossary_items

**Comment by lisaratner** [comment]
This glossary doc needs a review and needs to be run through the hemingway app: https://docs.google.com/document/d/1jnoRRRS51LcwrQr2LFEyg6pI1f9WlnlkSA-bFwXkCVo/edit?usp=sharing

**Comment by rossettistone** [comment]
I notice there are 30 items presently in the live glossary. Is there still more work to be done here?

**Comment by lisaratner** [comment]
yes, I set up Brenden to work on this next week

**Comment by lisaratner** [comment]
Teach Brenden CMS on Friday
