### ISSUE TITLE
Add Google Search to BP

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#120]
Make sure it captures search queries in Analytics.

Use searchbox styling from pilot.boston.gov

```html
<script>
  (function() {
    var cx = '003180083737835708997:hehme1kabdk';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>
```

**Comment by lisaratner** [comment]
add search icon to bar header

**Comment by lisaratner** [comment]
![search](https://cloud.githubusercontent.com/assets/16671878/16348269/52ca64c4-3a06-11e6-89f6-19d497f4445f.jpg)

**Comment by rossettistone** [comment]
After conversation yesterday, search will initially launch as a box below the hero image/video on homepage. No other points of access. Not using Boston styling.

**Comment by rossettistone** [comment]
Search is live, but still no data in GA. Docs suggest this can take "several hours" - will have to check back tomorrow. https://support.google.com/customsearch/answer/4513905?hl=en&ref_topic=4513743

**Comment by rossettistone** [comment]
Still no luck getting search data directly in GA. This Google support article (https://productforums.google.com/forum/#!topic/customsearch/3wLWAhBYdK4) suggests that it might be impossible, though it seems that some other folks have gotten it to work. As they're using the same setup we are, I'm not sure what else to try at this point.

We do have analytics directly in the Custom Search control panel (https://cse.google.com/cse/statistics/stats?cx=003180083737835708997%3Ahehme1kabdk), so we'll just have to look there. I'm gonna close this issue.
