### ISSUE TITLE
Header Bar Edits

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#133]
- [x] Make top header sticky on all screen sizes desktop and mobile. Foundation *should* be able to do this pretty easily
- [x] Change background color to #167FAB to be accessible
- [x] Font: Raleway
Weight: Regular
Size: 20px
- [x] Change all caps MENU -> Menu
- [x] Sizing
App bar height: 56dp 
App bar left and right padding: 16dp 
App bar icon top, bottom, left padding: 16dp 
App bar title bottom padding: 20dp https://material.google.com/layout/structure.html#structure-app-bar.

**Comment by lisaratner** [comment]
![header home](https://cloud.githubusercontent.com/assets/16671878/17905637/97ba4a3a-6928-11e6-9c49-64e3e30e3e68.jpg)

**Comment by rossettistone** [comment]
The math from Google's material design spec (linked above) only works if the navbar elements are 24px in height, as 24+16+16=56. In this case, the Menu button is 28px tall and the "Business Portal" words are specified to be 20px in height. I took the liberty of straying from Google's spec in favor of having all elements centered in the navbar.

**Comment by lisaratner** [comment]
@rossettistone sounds good, thanks for doing this!
- [ ] The one thing I would add is a back arrow icon for all pages other than HOME
