### ISSUE TITLE
Browser testing pass

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#136]
As of 6/13, the top *desktop* browsers in GA are:
• Chrome
• IE (80% on IE 11)
• Safari
• Firefox

The top *mobile* browser/device combos are:
• iPhone-Safari
• Nexus 5X-Chrome

Key things to check:
• Appearance of homepage
• Appearance of step page
• Function of side menu
• Function of glossary
• Function of checklist on step page
• Function of print button on `/checklist` page
• Function of "read more" text blocks on step page
• Function of Intercom

**Comment by lisaratner** [comment]
Browser Stack

**Comment by lisaratner** [comment]
Set standard for what we are going to test on
Samsung Mobile

**Comment by rossettistone** [comment]
A couple of browser-specific bugs were found, and recorded in #146
