### ISSUE TITLE
Redirect www to non-www

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#137]
- [x] Add CNAME from www to non-www.
- [x] Add server 301 from www to non-www.

**Comment by rossettistone** [comment]
Still waiting on response from city on this task.

**Comment by jemarqu** [comment]
Is this anything I can help with?

[cid:image001.png@01D1C170.99243580]

Jeremy Marquette
Department of Technology & Innovation (DTI) | City of Long Beach
phone: 562.570.5095 | email: jeremy.marquette@longbeach.gov
333 W. Ocean Blvd, Long Beach, CA 90802

**Comment by rossettistone** [comment]
Perhaps so - thanks! I'll reach out to you by email in a moment.

**Comment by rossettistone** [comment]
DNS got squared away, which makes www load the site, but a redirect at the server level is still required to 301 users from www to non-www. So that's the next (and final) thing.
