### ISSUE TITLE
Translation Button Fixes

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#149]
Is there a reason to not add a bunch more languages?
- [x] Add Japanese (came up in GA and library interview)
- [x] Add Russian (came up in GA)
- [ ] Look below for wireframe of  translation header treatment and add that in. Only on homepage
- [x] Hard to translate it back to english. Explore how to make that easier

**Comment by rossettistone** [comment]
Can definitely add Japanese. 

With regard to the other notes, here's the link for customizing the Translate button: https://translate.google.com/manager/website/

The second page of the form on that page shows the different appearances/UX that Google provides as options for this widget. Should be easy to swap out what we have with any of those styles once we choose one.

**Comment by lisaratner** [comment]
Thanks for the translate button ui info. Hmm. There aren't a ton of style options. 
I'm thinking an action bar globe  icon could do the trick. Would love to upload wireframes to the comments to show you what I mean but I can't figure out how to do that... is that possible in waffle?

**Comment by rossettistone** [comment]
Not sure how to do it from waffle, but you can drag and drop directly into the GitHub text box to upload photos, like this:

<img width="1280" alt="screen shot 2016-06-13 at 4 08 21 pm" src="https://cloud.githubusercontent.com/assets/1834981/16201032/b7949dd8-36dd-11e6-8965-4a6dc754b95e.png">

**Comment by lisaratner** [comment]
![translate](https://cloud.githubusercontent.com/assets/16671878/16348253/3c2c9480-3a06-11e6-8b8c-a0dcad69a27f.jpg)

**Comment by lisaratner** [comment]
Inspiration from Philly Site:
<img width="133" alt="screen shot 2016-08-22 at 5 22 20 pm" src="https://cloud.githubusercontent.com/assets/16671878/17905894/c28fb546-6929-11e6-82f5-d5a5855f43d5.png">
<img width="400" alt="screen shot 2016-08-22 at 5 21 07 pm" src="https://cloud.githubusercontent.com/assets/16671878/17905895/c2ad58da-6929-11e6-90ef-f7bad3acdf16.png">
<img width="791" alt="screen shot 2016-08-22 at 5 20 37 pm" src="https://cloud.githubusercontent.com/assets/16671878/17905896/c2c44e8c-6929-11e6-8885-137068276e81.png">


![header home](https://cloud.githubusercontent.com/assets/16671878/17905876/a50181bc-6929-11e6-9b56-ca806e432199.jpg)
