### ISSUE TITLE
Generate content for empty bizport pages

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#173]

**Comment by patrickm02L** [comment]
The following pages look to need content:
PLAN
- Get an Idea
APPLY
- Determine Business Location
GROW
- Pay Your Business Taxes
- Obtain Funding
- Marketing
- Networking

**Comment by rossettistone** [comment]
@patrickm02L Can you split this into individual cards, in particular with a card(s) for items to be knocked out this week?

**Comment by patrickm02L** [comment]
Created individual issues for each section above.
