### ISSUE TITLE
Header Bar Edits

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#179]
App bar height: 56dp 
App bar left and right padding: 16dp 
App bar icon top, bottom, left padding: 16dp 
App bar title bottom padding: 20dp https://material.google.com/layout/structure.html#structure-app-bar.

Font: Raleway
Weight: Regular
Size: 20px

Change all caps MENU -> Menu

**Comment by lisaratner** [comment]
![bizport header](https://cloud.githubusercontent.com/assets/16671878/17881886/a43daf6a-68bd-11e6-9474-4811b7d7fe73.png)
