### ISSUE TITLE
"My Checklist" Edits

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#18]

**Comment by rossettistone** [comment]
Is this different from, or superceded by, #59?

**Comment by lisaratner** [comment]
[ ] Double check step language from BizPort Copy
[ ] Add "Step 1" etc. to each header
[ ] Link each checklist header back to the step page it corresponds to
[ ] Make checklist header font dark_blue and underline to indicate it is a link
[ ] Add Robert Garcia pop-up when all items are checked off
[ ] Use higher resolution white checkmark
[ ] Link "My Checklist" from each Step page to the "My Checklist" page
[ ] Change "Checklist" in navbar to "My Checklist"
