### ISSUE TITLE
Link Mayor's video on homepage

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#180]
https://youtu.be/vA3X1WK_F7o
Add playbutton overlay to city of long beach image so when you click, it popups the video

**Comment by rossettistone** [comment]
And do we have a particular deadline on this story?

**Comment by lisaratner** [comment]
Hey Mark, We just got a request to put this up this week. Is that manageable?

**Comment by rossettistone** [comment]
More spec needed first. See questions above.
