### ISSUE TITLE
Detailed Instructions for Intercom to CMS flow

### ISSUE THREAD

**Issue by patrickm02L** [rossettistone/bizport#184]
Create a one-pager for review by Thursday that describes the feedback loop flow. Should be easy enough for anybody to read and do on their own.

**Comment by patrickm02L** [comment]
I have included a How-To of the workflow in the "Intercom Ticket Plan" See table of contents of this doc: https://docs.google.com/document/d/1IG9oituV6GPumEv2-It5CRPE3ZCZkpu5_8fGmu50Zog/edit?usp=sharing

**Comment by rossettistone** [comment]
:+1:
