### ISSUE TITLE
Change Translate from Filipino to Tagalog

### ISSUE THREAD

**Issue by patrickm02L** [rossettistone/bizport#186]
Request through Intercom 

Can we change the translate feature from Filipino to Tagalog?

**Comment by lisaratner** [comment]
No, google calls it Filipino.

On Tuesday, July 12, 2016, Patrick McDonnell <notifications@github.com>
wrote:

> Request through Intercom
>
> Can we change the translate feature from Filipino to Tagalog?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rossettistone/bizport/issues/186>, or mute the thread
> <https://github.com/notifications/unsubscribe/AP5khkhi_c1dbC3c4i56Ei-Eeh6bQjf1ks5qU70wgaJpZM4JKjql>
> .
>


-- 
Lisa Ratner
User Experience Designer
*UX-by-Lisa.com <http://UX-by-Lisa.com>*
LisaARatner@gmail.com
(650) 207-3682

**Comment by patrickm02L** [comment]
@lisaratner thank you for the update, I am going to close this issue.
