### ISSUE TITLE
Get CfA style review of RM from David

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#193]
Daniella (and Norris, on PTO) is torchbearer for the standardization of Code for America styles and UX. She should review our interface and give feedback about what changes would bring it in line with CfA interface goals.

**Comment by lisaratner** [comment]
Sent them the prototype via slack. Awaiting their feedback.

**Comment by lisaratner** [comment]
Make appointment with them for Monday

**Comment by lisaratner** [comment]
adding notes to a user testing document
