### ISSUE TITLE
Page Content: Finance Your Business

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#2]
*From Patrick*
2. Finance Your Business
LEARN

You have a plan, now you need capital. You need money to start your business and to sustain it. Let’s identify where to find resources.  

You will need:
Savings
Private Loans
City Loans
DO
Define your Starting Capital
Calculate your monthly operating costs
Create a budget for the year to track costs and incoming revenue.
Work with the Long Beach Small Business Development Center to finalize

**Comment by rossettistone** [comment]
I'm thinking to focus this page on the *raising* money aspect of financing, rather than operational finance, which I think is more a component of the business plan. What do you think?
----------

LEARN

You have a plan, now you need capital. You need money to start your business and to sustain it. Let’s identify where to find resources. Be sure that you prepare enough money to run your business for at least the first several months, as it may take time to set up before you have enough customers to be profitable.

Most businesses cost a significant amount of money to start. Using the calculations and estimates from your business plan (link to business planning), decide if you have enough money to begin, or if you need additional money first. 

Here are some ways to get additional money if you need it:
• __City Loans__: The City of Long Beach has a loan program for small businesses. Loans are based off of the quality of your business plan as well as your resume and other personal documents. Credit score is part of the decision, but a low credit score might not prevent you from getting a loan. More information is available on the city's website: (link)
• __Private Loans__: 

DO
1) Calculate how much money you'll need ("starting capital").
2) Determine how much money you'll need to raise before starting your business.
3) Work with the Small Business Development Center (SBDC) and the city's Economic Development Department (EDD) to find city and bank loans that will help you get started.

(Primer Peso goes here, eventually)

**Comment by patrickm02L** [comment]
3rd paragraph:
Original: Most businesses cost a significant amount of money to start.
Change: Starting a can be expensive.

**Comment by rossettistone** [comment]
Sounds good to me. Changed.
