### ISSUE TITLE
Survey edits

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#206]
Add a why to CTA

Change name to "tap here to begin"

"You can take this survey at any point of your process getting a business up and running."

Dangerous back button, takes you completely out of the survey / site

Remove Intercom button from survey page

Question 3) too hard to compare the options since there are so many options and the icons are so big. 

6) consider question -> what would you like more information about

7) Do you have any of the following: (check all that you have)
add a none option

IF they click a 1 or 2 star, ask them more questions about what happened. 

How could we have served you better, how could we have been more useful?

**Comment by lisaratner** [comment]
@rossettistone Can we remove the Intercom button from survey page? Is that possible?

**Comment by rossettistone** [comment]
Yep! Logging.
