### ISSUE TITLE
Contact Page Content Generation

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#207]

**Comment by lisaratner** [comment]
Better surface who to contact when so everyone feels like they know who to talk to.

**Comment by rossettistone** [comment]
Figure out what contact information is frequently needed for an entrepreneur (whether City or outside), and provide links or references to it here.

**Comment by lisaratner** [comment]
![contact us - default](https://cloud.githubusercontent.com/assets/16671878/17757626/364bce34-649d-11e6-8f5b-a1eae1632d10.jpg)
![contact us business licensing](https://cloud.githubusercontent.com/assets/16671878/17757627/364c580e-649d-11e6-9bdc-a219edf1fb55.jpg)

**Comment by lisaratner** [comment]
@heidiwiersma would love your feedback: https://invis.io/PX6O6B79K#/182045439_Contact_Us_-_Default

**Comment by lisaratner** [comment]
![Uploading Contact Us - Default.jpg…]()
![contact us - lb city hall](https://cloud.githubusercontent.com/assets/16671878/17827563/afd63e32-6633-11e6-9471-7e0498bdd7bb.jpg)
![Uploading Contact Us-  Business Licensing.jpg…]()

**Comment by lisaratner** [comment]
Talk to Dale about Development Services Page

**Comment by lisaratner** [comment]
talk to jacquie medina about development page

**Comment by rossettistone** [comment]
[Business license process.pdf](https://github.com/rossettistone/bizport/files/508401/Business.license.process.pdf)
