### ISSUE TITLE
Update Menu icon in top bar

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#211]

**Comment by lisaratner** [comment]
https://drive.google.com/open?id=0B6V6JxtkVuf9R2tqMFlxY1pJZVU blue icon


https://drive.google.com/open?id=0B6V6JxtkVuf9bGowYjhVQnZKNEU white icon

**Comment by lisaratner** [comment]
Profile icons and Menu icon

**Comment by rossettistone** [comment]
Profile icon updated as part of Login (#28). Menu is actually presently done in CSS, not with an icon/image. I'll change this story to refer to the menu icon only, and see what the best approach is (modify CSS or replace with image). 

Also moving this out of this sprint, as I've already got a full set of commitments for this week.

**Comment by lisaratner** [comment]
Instead of an Icon, let's just change it to the word Menu with a border around it. User just aren't getting that the icon means menu
