### ISSUE TITLE
Sticky Checklist on Desktop

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#229]
Sometimes it sticks on the left hand side when you scroll and sometimes it doesn't.
Can we make it always sticky

**Comment by rossettistone** [comment]
Unable to reproduce the problem. Can you describe a set of steps that cause it not to stick when scrolling?

**Comment by lisaratner** [comment]
hmm, I scrolled and it wasn't sticky haha. I'll try to be more aware.

**Comment by rossettistone** [comment]
For now, closing as unreproducable. We can re-open if this recurs and we have reproduction steps.
