### ISSUE TITLE
Location toggle collapse instead of disabling

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#234]
If user selects "solo home office", instead of greying out the steps, remove them and have the steps collapse. Add number of steps to the button. Solo home office: # Brick and Mortar : #

**Comment by rossettistone** [comment]
Revision: Step removal should be animated. Animation TBD.

**Comment by rossettistone** [comment]
@lisaratner ^^

**Comment by lisaratner** [comment]
@rossettistone 
Ideally the transition will 
1) fade out the irrelevant steps (0.25 sec)
2) Then Slide the remaining steps up the y axis (0.25 sec)

Do you still need me to find the actual code for that css?

**Comment by rossettistone** [comment]
Ended up using jQuery `slideUp()` as a quick solution for the animation, though it doesn't involve the "fade out" part. Can circle back on the fade at a later time.
