### ISSUE TITLE
Chat with Vanessa re Online Biz License Application

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#262]
Vanessa is the TID point person here.
Would be great to know how we can combine login info so the user doesn't have to fill it out twice. This feel different from the Rhythm project.

**Comment by lisaratner** [comment]
Ask her if we can add a checkbox to the online and paper application and a form field:
1) (checkbox) I have a Bizport Account
2) Email address used for the BizPort Account 
This way we can link the accounts and track if that biz license was renewed in a year

**Comment by rossettistone** [comment]
After the conversation with Brett and Heidi yesterday morning, sounds like this might not be a ripe opportunity. Backlogging for now.
