### ISSUE TITLE
Why Long Beach

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#278]
Integrate why long beach and its unique qualities
Incentive programs

**Comment by lisaratner** [comment]
Create this page after "Get an Idea"
"Why Long Beach
The unique factors this city has for businesses to thrive" or something like that

**Comment by lisaratner** [comment]
Add link to LA BizPort as well

**Comment by rossettistone** [comment]
Happy to create this page. N.B. new pages can be created in the CMS by clicking the "Add Child Page" button on the parent page (in this case "plan"):
<img width="798" alt="screen shot 2016-08-19 at 11 07 53 am" src="https://cloud.githubusercontent.com/assets/1834981/17819533/3a526ef0-65fd-11e6-93a1-abe1789fb212.png">
