### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#28]
User Story: As an entrepreneur, I want to be able to save my checklist progress

- [x] Save button ("Save My Progress") below all checklists -> Sign In/Up page (devise default)
- [x] Header of sign-up page should read "Create an Account"/"to save my checklist"
- [x] Redirect back to originating page after sign-in, and include flash banner (e.g. "logged in successfully")
- [x] "Login"/"Signup" words in header on *desktop* view (mobile too cramped to fit)
- [x] Checklists should be pre-checked when logged-in users view step or checklist pages
- [ ] User dashboard page ("My Account") including PW reset and link to "My Checkilst" page
- [x] Send emails for account events (Amazon SES?)
- [x] Add login area to top of menu (photo placeholder, "logout" button)

**Comment by rossettistone** [comment]
Now that we have user accounts set up, albeit invisibly, we pretty much just need wireframes to start in on this. That probably includes a sign-up flow, sign-in flow, and minimal account dashboard (for changing password).

**Comment by rossettistone** [comment]
From #112: - [ ] Once login is created, add a save button underneath the checklists. Add a save button as the sticky CTA on the My Checklist page

**Comment by lisaratner** [comment]
![menu open](https://cloud.githubusercontent.com/assets/16671878/16471398/49e105de-3e11-11e6-8025-c21d022fee2d.jpg)

**Comment by lisaratner** [comment]
Found this older version of triggering
![get an idea - checked - trigger - dropdown](https://cloud.githubusercontent.com/assets/16671878/16471431/89ed5236-3e11-11e6-9341-2a251e16a17c.jpg)

**Comment by lisaratner** [comment]
![1 create an account menu](https://cloud.githubusercontent.com/assets/16671878/17116887/a3af8966-526e-11e6-9422-69dc00efb505.jpg)
![2 logged in menu](https://cloud.githubusercontent.com/assets/16671878/17116888/a3b10f66-526e-11e6-851c-732f1c0dc204.jpg)

**Comment by rossettistone** [comment]
Notes from review w/Lisa, 7/26:
- [ ] *all* logins should redirect to page where sign-in started
- [ ] individual step pages *shouldn't* redirect back to checklist
- [x] split email into foo|@bar.com
- [ ] Add h2 "to save your checklist progress" on Sign Up page (if coming from checklist with :updates set)
- [x] "Forgot your password?" under password field on Sign In page
- [x] "Sign Up" header -> "Create an Account"
- [x] "Sign Up" button -> "Create an Account", `.expanded` button to lighter shade of gray
- [x] "Log In" button on Sign Up page -> lighter shade of gray
- [x] -Put *above* BizPort title bar
- [x] -Dark blue, white text
