### ISSUE TITLE
Change readmore heightMargin

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#287]
Only collapse copy with a readmore button when there's an especially long section of text. The setting is currently 300px, but should be something higher - maybe 500px? Let's work this one out together.

**Comment by rossettistone** [comment]
Pausing on this - seems like simply removing readmore from a bunch of the sections did the trick.

**Comment by rossettistone** [comment]
@lisaratner Was removing readmore from sections (by removing the class) a sufficient fix, or should we keep this card open as well?

**Comment by lisaratner** [comment]
closing
