### ISSUE TITLE
Homepage Toggle Update

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#290]

**Comment by lisaratner** [comment]
![home - create an account](https://cloud.githubusercontent.com/assets/16671878/17822581/d3e132ea-660c-11e6-96df-a42b38213e4f.jpg)
![Uploading Home - My Profile.jpg…]()

**Comment by lisaratner** [comment]
https://invis.io/PX6O6B79K#/184502548_Home_New_User
https://invis.io/PX6O6B79K#/184502549_Logged_In

**Comment by lisaratner** [comment]
![brick_mortar_87343-200_grey](https://cloud.githubusercontent.com/assets/16671878/18606137/4deb47a6-7c5b-11e6-9d93-93bfaa347ee3.png)
![home_based_151727-200_grey](https://cloud.githubusercontent.com/assets/16671878/18606138/4e08e4fa-7c5b-11e6-91e7-682daee27564.png)

**Comment by lisaratner** [comment]
Can you update the page title background color to match the top menu banner color? Thanks!

**Comment by rossettistone** [comment]
This design (mostly) supercedes the Invision documents above. In the event of discrepancies, ask Lisa.

![home - updated](https://cloud.githubusercontent.com/assets/1834981/18919273/791d11b6-856b-11e6-89ea-b3f0e45457ea.jpg)

**Comment by rossettistone** [comment]
Per Lisa's request on 9/28, we're calling this "done" until further user testing happens.

**Comment by rossettistone** [comment]
Per Lisa's request on 9/28, we're calling the toggle part of this "done" until further user testing informs future changes.

**Comment by lisaratner** [comment]
Yes to the toggle update

**Comment by lisaratner** [comment]
![launch](https://cloud.githubusercontent.com/assets/16671878/19045997/4680c016-8950-11e6-8571-7558105754c7.jpg)

**Comment by lisaratner** [comment]
@rossettistone ^^
