### ISSUE TITLE
Create an Account Page Edits

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#296]
- [x] Change "Password confirmation" to  "Confirm Password"
- [x] Add line about library helping create an email address
- [x] Change "Sign-up" to "Save"

**Comment by lisaratner** [comment]
![create an account edits](https://cloud.githubusercontent.com/assets/16671878/17905791/3bda4d4a-6929-11e6-91c1-6473d629b9bd.jpg)

**Comment by rossettistone** [comment]
@lisaratner Can you add where the library link should go to?

**Comment by rossettistone** [comment]
Add subheader language per comp above.
