### ISSUE TITLE
Page Content: Find a Location

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#3]
*From Patrick*
3. Find A Location
LEARN
The time has come to find a place for your business. It may sound easy, but there are a lot of things to take into account before signing the lease.  

You will need:
Survey of area
Zoning Check 
Real Estate Broker
DO
Identify a number of properties where you would like to locate. 
Check with the Planning/Zoning Desk on the 4th floor to see if you’re ‘business use’ will fit into the current zoning of the property. 
Negotiate the lease with your Broker.

**Comment by rossettistone** [comment]
LEARN
The time has come to find a place for your business. It may sound easy, but there are a lot of things to take into account before signing the lease.

As you select a location for your business, consider:

• Customers: Pick a location that your target customers can easily reach.
• Rent: Make sure that you can afford the rent, based on the revenue and cost expectations from your (business plan)
• Zoning: Different business types are only allowed in certain parts of the city, and it is illegal to run a business in a building that is not zoned for that type of activity. Always check with the city (link) before signing a lease.


You will need:
Survey of area
Zoning Check 
Real Estate Broker

DO

> NOTE: Do not sign a lease until you've checked with the city to make sure the building can be used for your type of business. 

1) Identify several locations that would well-suited for your business. Real estate agents can help with this process.
2) Check with the planning and zoning desk on the 4th floor of city hall (link) to see if your business is allowed in the locations you've selected.
3) Negotiate the lease with the landlord. Real estate brokers can help with this step. (more advice is needed here on common negotiable lease terms)

**Comment by patrickm02L** [comment]
:+1:

**Comment by lisaratner** [comment]
(Communicate value of BIDs. Map of BID areas. Note that it is an extra fee)

**Comment by rossettistone** [comment]
BID information added.
