### ISSUE TITLE
Info architecture

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#303]
business space types: Brick and Mortar
Site Selection: but don't sign a lease yet
Zoning: check to see if your business type is allowed at that site
Negotiate your lease: then sign it

consider Merging Negotiate your lease in with site selection and zoning

**Comment by lisaratner** [comment]
Need more on ADA requirements

**Comment by rossettistone** [comment]
This story seems very general to me. Can you elaborate on what the work is required to complete and close this story?

**Comment by lisaratner** [comment]
I'm trying to solidify the order of operations for the apply section, especially where the filter comes into play.

**Comment by rossettistone** [comment]
- [ ] Remove # of steps from toggle
- [ ] New language: "Business Property" and "Home-Based"
- [ ] New language: "Choose property type:" (no "learn more" link)
- [ ] Move "Determine Property Type" page to bottom of Plan section, and change subtitle of page to "Business property? Mobile? Home?

**Comment by lisaratner** [comment]
@rossettistone Can you make the following updates? I think it will really clarify things for the user. If we have too many pages I see areas where we can combine such as site plan check, permits, and inspections. 

-[ ] Separate Site Selection and Zoning Check into 2 pages. This way when you select Home Based business the results will have 4 pages underneath: 1) Zoning Check, 2) Register Your Business 3) Apply for a Business License 4) Manage Your Business License

- [ ] Page Title: Site Selection: but don't sign a lease before checking zoning
- [ ] Page Title: Zoning Check: Is your business type is allowed at that site?
