### ISSUE TITLE
LBDS Intercom updates

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#336]
- [x] update profile image with circular seal instead of LB logo

- [x] Change name on intercom from Long Beach Development Services -> Development Services

- [ ] ~~Get Dale and Structural representative onto intercom to more easily route the questions.~~

- [ ] ~~Teach Medina's assistant how to use intercom.~~

**Comment by rossettistone** [comment]
For the time being, we're pausing onboarding of new LBDS folks. Jacquie Medina will be the point of contact for the time being, and will forward questions to others for expert questions.
