### ISSUE TITLE
Obtain domain name

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#34]

**Comment by rossettistone** [comment]
Just emailed Scott and Jeanne to check up on the status of this.

**Comment by rossettistone** [comment]
For the moment we've got cfa.longbeach.gov. Seems like a great provisional domain for a soft launch. We can get other domains as we need 'em. 

I'll close this as soon as I've got a demonstrated successful launch on that domain name, since I'm not sure how the city does DNS and all that.
