### ISSUE TITLE
Page Content: Choose a Name

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#4]
*From Patrick*
4. Choose A Name
LEARN
Let’s make your name official. You’ve chosen a name, now you will have to register it with the State and County of California so you can start ‘Doing Business As’ your company,

You will need:
Fictitious Business Name Application
DO
Go to the DBA and register your name with the State and County.

**Comment by rossettistone** [comment]
Since this is the point when a person starts paying money and doing paperwork, I think it would be valuable to have a strong visual warning not to proceed further until steps 1-3 (planning, financing, location) are complete.

Btw, is it necessary to register a FBN with the state? I thought it was county only. Will have to check before we finalize this.
----------

LEARN
Let’s make your name official. You’ve chosen a name, now you will have to register it with the State of California and County of Los Angeles so you can start "Doing Business As" (DBA) your company:

> NOTE: Do not apply for a business name or file other paperwork until you're done (writing a business plan), (planning your finances), and (selecting a location). Paperwork can be expensive, and it's important that you're done planning before you begin applying.

You will need:
Fictitious Business Name Application (link to document)
DO
Register your name with the county.

**Comment by patrickm02L** [comment]
FBN is county only. Here's the link for Los Angeles County: http://lavote.net/home/county-clerk/fictitious-business-names/general-info?CFID=1867971&CFTOKEN=9bc64d5adbfed9e4-717E3AE7-D1AB-BD83-2D74104C78C1DC19

First time filing for FBN is $26 plus $5 search fee. I'm wondering if we need the NOTE in this section?

**Comment by rossettistone** [comment]
Yeah, the "note" does seem a little heavy-handed given how cheap the fee is. My reason for including it was because this is the "commitment" moment that we talked about, after which every action begins to cost money and require paperwork. We could move the note to step 5 (register), but I think steps 1-3 are the "planning" phase, and step 4 represents a change in intensity that I want the entrepreneur to feel.

**Comment by rossettistone** [comment]
Argh, another chicken/egg problem. The FBN application wants business address, but the business license app wants FBN! Which first?
<img width="588" alt="screen shot 2016-02-27 at 3 15 36 pm" src="https://cloud.githubusercontent.com/assets/1834981/13376041/196e4298-dd65-11e5-97ed-a06ecc87f5f8.png">
