### ISSUE TITLE
Page Content: Register Your Business

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#5]
*From Patrick*
5. Register Your Business
LEARN
You have a name that you’ve registered at the State and County level, now you need to ‘Register in your City.’ 

You will need:
Long Beach Business License Application
DO
Fill out the Long Beach Business License Application.
Go to the 4th floor of Long Beach City Hall to file.
Pay for your license and fees on the 4th floor.

**Comment by rossettistone** [comment]
*I think this is the right moment to include federal and state filing requirements as well.*
*I wonder if it's worth mentioning that things like LegalZoom exist? Or is that too much of an endorsement?*

----------

LEARN
Now that you have a business name registered with the county, you're ready to register your business with the federal, state, and city governments.

Registering your business costs money, and fees will vary based on your type of business, location, and number of employees.

If your business is located in one of Long Beach's Business Improvement Districts (BIDs) (link), you will be required to pay a BID fee as well. This money is used to improve the environment for businesses in the BID areas, including picking up trash, removing graffiti, hosting public events, and providing helpful resources to local businesses.

DO
Apply for the following in order:
1) [Federal Employer Identification Number Application](https://www.irs.gov/Businesses/Small-Businesses-&-Self-Employed/Apply-for-an-Employer-Identification-Number-(EIN)-Online)
2) [California State Board of Equalization Seller's Permit Application](http://www.boe.ca.gov/info/reg.htm)
3) [City of Long Beach Business License Application](http://www.longbeach.gov/finance/business-info/business-licenses/business-licenses/). Fill out this form and take it to the 4th floor of City Hall. While it is possible to mail the form in, visiting the office in person will ensure that you're able to ask and answer any questions that may come up as city staff review the form.

**Comment by patrickm02L** [comment]
:+1: content

This is definitely the right step for Legal Zoom. I don't know if we should mention it or not?

**Comment by rossettistone** [comment]
I'm gonna leave it out for now. That can be a later addition/discussion.

**Comment by rossettistone** [comment]
Content has been moved to Google doc for further discussion: https://docs.google.com/document/d/1l5PIDZLrkQpMwqDwpxD-TpEtbE6IyWeQLdXvygtjQWU/edit
