### ISSUE TITLE
Page Content: Permits and Licenses

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#6]
*From Patrick*
6. Permits and Licenses
LEARN
If you are starting a business in a building that needs to be renovated you will need to get permits to make changes. In order to get permits, you must submit drawings called plans and/or construction documents to the city.

You will need:
---- Application
Permit Applications for building renovations or changes to the property
Architect or Contractor to help create drawings of your building changes. 
Plans and Construction Documents that show new changes.

If you are starting a business that has health requirements, you will need to get licenses to make sure you can operate safely.

License Applications to operate safely.
DO
Fill out Applications
Submit Applications & Physical copies of the Plans to the 4th Floor.
Pay permit fees.

**Comment by rossettistone** [comment]
*I think this is the right place to also talk about various "licenses" (food, alcohol, massage, etc.) that a business owner might need.*

---------

LEARN
#### Licenses
Some business types require special licenses to operate. Examples include food preparation, alcohol sales, tobacco sales, or massage services. City staff can tell you what licenses your business might need to operate.

#### Permits
Permits are proof that your building and facilities follow city rules ("code") and are safe for you, your employees, and your customers. If you are starting a business in a building that needs to be renovated, you will need to get permits to make changes. In order to get permits, you must submit drawings ("plans") and construction documents to the city.

Construction rules can be complicated. For large projects, a professional architect or contractor may be able to offer helpful advice and planning assistance. They can also create the necessary drawings and plan documents you'll need to show to the city.

In order to apply for permits, you will need:
• A completed [Development Services Permit Application](http://www.lbds.info/civica/filebank/blobdload.asp?BlobID=4336)
• Plans and construction documents that show new changes
*(is a licensed contractor legally __mandatory__, or just recommended?)

DO
1) Fill out permit applications
2) Submit applications & physical copies of the plans to the 4th floor of City Hall
3) Pay permit fees

**Comment by patrickm02L** [comment]
3rd paragraph: (clarification)
Plans = site plans, Construction Documents (CDs) show details of a building's structure. Plans and construction documents are both types of 'drawings.' 

A licensed contractor is not mandatory, you can serve as your own contractor on small jobs (i.e. fences, landscaping, small addition to your house.) However, Construction Documents will usually have a stamp from a licensed architect showing they meet structural standards.

**Comment by rossettistone** [comment]
*Good points. How about this amended 3rd paragraph?*

Construction rules can be complicated. A professional architect or contractor may be able to offer helpful advice and planning assistance, as well as create necessary site plan drawings and construction documents (CDs). For large projects, you may need a licensed architect to approve your plans before showing them to city staff.

**Comment by rossettistone** [comment]
Content has been moved to Google doc for further discussion: https://docs.google.com/document/d/1l5PIDZLrkQpMwqDwpxD-TpEtbE6IyWeQLdXvygtjQWU/edit
