### ISSUE TITLE
Page Content: Building and Inspections

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#7]
*From Patrick*
7. Buildings and Inspections
LEARN
Now that you’ve submitted your plans, and they have been reviewed, you can start scheduling inspections to make sure your building complies with Long Beach city code. 

You will need:
Inspection Appointment Website
Copy of Plans
DO
Schedule Appointment online
Be available during Inspection time window
Have copy of plans available for review when the inspector shows up

**Comment by rossettistone** [comment]
LEARN
As you complete each phase of construction, you'll need to have city inspectors visit to ensure that the work meets the safety standards in the Long Beach city code.

There are several types of inspections, including fire, plumbing, health, mechanical, and electric. You may have to have several inspections from each category as construction proceeds. When you finish construction, you'll need a final inspection for each category of work you've done.

The cost of these inspections is already included in the fees you paid with your permit applications.

DO
1) Schedule appointments [by phone] (http://www.lbds.info/building/inspection_services/) (in future, online). Inspections can usually be scheduled for the next business day.
2) Be available at your business when the inspector arrives.
3) Have a physical copy of your plans available for the inspector to review.

**Comment by rossettistone** [comment]
Just found some additional detailed steps on the city website here: http://www.lbds.info/faqs/categoryqna.asp?id=19#157

May be worth reviewing and comparing.

**Comment by patrickm02L** [comment]
Paragraph 2: (Amendement)
When you finish construction, you'll need a final inspection for each category of work you've done including fire, plumbing, health, mechanical, and electric. You may have to have several inspections from each category as construction proceeds. 

Here's the municode for a CO: 
https://www.municode.com/library/ca/long_beach/codes/municipal_code?nodeId=TIT18BUCO_CH18.08CEOC

**Comment by rossettistone** [comment]
:+1:

**Comment by rossettistone** [comment]
Content has been moved to Google doc for further discussion: https://docs.google.com/document/d/1l5PIDZLrkQpMwqDwpxD-TpEtbE6IyWeQLdXvygtjQWU/edit
