### ISSUE TITLE
Page Content: Open Business

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#8]
*From Patrick*
8. Open Business
LEARN
You have gone through the entire process and now you’re ready to open. 

If you have a brick-and-mortar site, you’ve gone through the 4th floor of Long Beach City Hall and you’re at the final step. Get your Certificate of Occupancy.

You will need:
Certificate of Occupancy Application
DO
Submit Certificate of Occupancy Application
Get final approval. 
Start doing business!

**Comment by rossettistone** [comment]
LEARN
Once your business license has been issued and all permits approved, the city will issue you a certificate of occupancy for your location. This certificate indicates that your building and facilities meet city safety rules, and allows for utilities (power, water, and gas) to be connected to the building.

*Oddly enough, I don't see a CofO application. There's only an application for temporary ones. Perhaps the CofO is automatically issued?*
DO
1) Receive Certificate of Occupancy
2) Start doing business!

> Many free services are available if you need help as you begin doing business. Search here: (Primer Peso link?)

**Comment by patrickm02L** [comment]
A Temporary Certificate of Occupany may be obtained if part of the building are habitable. It allows for a 90 days period to operate in those TCO areas. 

A CO is issued after a final walk-through inspection.

**Comment by rossettistone** [comment]
Ok, adjusted above to indicate that the CO is automatic, and does not require an application.

**Comment by rossettistone** [comment]
Content has been moved to Google doc for further discussion: https://docs.google.com/document/d/1l5PIDZLrkQpMwqDwpxD-TpEtbE6IyWeQLdXvygtjQWU/edit
