### ISSUE TITLE
Desktop Style Edits - wireframe

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#99]
- [x] align navbar to right 
- [x] align "welcome to bizport" to match left side of BizPort Logo
- [x] Change Navbar font to Raleway
- [x] Thicken weight of navbar font

**Comment by lisaratner** [comment]
@rossettistone Got some insight into how to handle the desktop view homepage:

**Comment by lisaratner** [comment]
![homepage desktop view](https://cloud.githubusercontent.com/assets/16671878/17196396/2fdca030-5419-11e6-9d12-141f8c77186f.jpg)

**Comment by rossettistone** [comment]
Is this still the gameplan for the desktop homepage? Just checking in case this has fallen out of date.

**Comment by rossettistone** [comment]
Closing as out of date.
